"use client"

import './globals.css'
import {Provider} from "react-redux";
import "./globals.css"
import store from "./store"


export const metadata = {
    title: 'notes-app',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <Provider store={store}>
            <html lang="en">
            <body>{children}</body>
            </html>
        </Provider>
    )
}

